defaults: &defaults
  working_directory: /tmp/docker_on_debian_build
  docker:
    - image: mumblepins/docker-on-debian-circleci
      environment:
        DOCKER_IMAGE: "mumblepins/docker-on-debian-circleci"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            set -ex
            VERSION=$( cat VERSION | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' )
            GIT_COMMIT=$( git rev-parse --short HEAD )
            BUILD_DATE=$( date -u +"%Y-%m-%dT%H:%M:%SZ" )
            GIT_URL=$( git config --get remote.origin.url )
            # Convert github ssh repo to https
            if echo "$GIT_URL" | grep -q "git@github.com"; then
              GIT_URL=$( echo "$GIT_URL" | sed -r 's|git@github.com:|https://github.com/|' )
            fi
            echo "export VERSION=\"$VERSION\"" >> $BASH_ENV
            echo "export GIT_COMMIT=\"$GIT_COMMIT\"" >> $BASH_ENV
            echo "export BUILD_DATE=\"$BUILD_DATE\"" >> $BASH_ENV
            echo "export GIT_URL=\"$GIT_URL\"" >> $BASH_ENV
            docker build \
              --build-arg BUILD_DATE="${BUILD_DATE}" \
              --build-arg VERSION="${VERSION}" \
              --build-arg VCS_URL="${GIT_URL}" \
              --build-arg VCS_REF="${GIT_COMMIT}" \
              -t ${DOCKER_IMAGE}:${VERSION} .
      - run:
          name: Save Docker Image to Workspace
          command: |
            set -ex
            mkdir -p workspace
            time (docker save ${DOCKER_IMAGE}:${VERSION} | lz4 -zc > workspace/image.tar.lz4)
            cat $BASH_ENV > workspace/BASH_ENV_SAVE
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar.lz4
            - BASH_ENV_SAVE
      - store_artifacts:
          path: workspace

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace
      - run: cat workspace/BASH_ENV_SAVE >> $BASH_ENV
      - setup_remote_docker
      - run:
          name: Docker Image Load
          command: |
            set -ex
            time (lz4 -cd workspace/image.tar.lz4 | docker load)
      - deploy:
          name: Docker Hub Deploy
          command : |
            set -ex
            echo $PWD
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag ${DOCKER_IMAGE}:${VERSION} ${DOCKER_IMAGE}:latest
            docker push ${DOCKER_IMAGE}:${VERSION}
            docker push ${DOCKER_IMAGE}:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9.]+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9.]+$/


